OTP-19 and openssl 1.0.x compatibility
gbour/letsencrypt-erlang pull request #16
Opened 2020-03-18 07:56 UTC by mworrell

This changes a couple of things:

 * Sets min OTP version to 19, as it does indeed work excellent with OTP-19
 * Uses the openssl 1.0.x code to add the SANs to the certificate, as quite some machines are still using a late version of openssl 1.0.x
 * Enables the Dialyzer Makefile target
 * Small start with additional typing of arguments

2020-04-07 21:02 UTC, gbour commented
Hi @mworrell 
Thanks for your valuable contributions. I will review this MR quickly

2020-04-09 19:36 UTC, gbour requested changes

2020-04-09 19:36 UTC, gbour commented on Makefile
> +	./rebar3 dialyzer;\
```suggestion
	./rebar3 dialyzer;
```

2020-04-09 19:36 UTC, gbour commented on src/letsencrypt_ssl.erl
>      FileName = CertsPath++"/"++KeyFile,
this does not works well if either `CertsPath`or `KeyFile` or both are binary strings

2020-04-09 19:36 UTC, gbour commented on src/letsencrypt_ssl.erl
>      KeyFile  = CertsPath ++ "/" ++ Domain ++ ".key",
same comment as previous one

2020-04-10 10:07 UTC, mworrell commented on src/letsencrypt_ssl.erl
>      KeyFile  = CertsPath ++ "/" ++ Domain ++ ".key",
Indeed, fixing.

2020-04-10 10:09 UTC, mworrell commented
Weird I pushed some changes to the otp-19 branch and the build passes, but I don't see the updates here.

2020-06-25 09:29 UTC, mworrell commented
@gbour could you have another look?

Is also added now:

 - Support for SANs using _slave_ mode
 - Replace Jiffy with JSX to fix problems with compilation on OTP-23

2020-09-03 07:57 UTC, mworrell commented
Hi @gbour. GitHub doesn't show me clearly what changes you requested are still open.  Could you have a look?

2020-11-24 07:46 UTC, mworrell commented
Hi @gbour, do you have time to have a look at this?

2021-01-13 11:56 UTC, mworrell commented
Ping :)

2021-03-30 20:13 UTC, Olivier-Boudeville commented
Hi Marc, thanks for these improvements that, as I understand, could not be (yet) integrated here (FWIW, I took inspiration from them for https://github.com/Olivier-Boudeville/Ceylan-LEEC - at least for the SAN certificates); thanks to you and Guillaume for bringing ACME support to the Erlang community!

2021-03-31 07:22 UTC, mworrell commented
Hi @Olivier-Boudeville, thanks for the nice words, and good to know that this code is of good use for others as well. As for the pending status of this request, I guess that @gbour is very busy with other things at the moment.

2022-06-10 08:57 UTC, closed without merging